### ISSUE TITLE
Supported Bitnami image list

### ISSUE THREAD

**Issue by ZCube** [ZCube/bitnami-compat#43]
## Image List

---

* Image
  * Component

---

* [x] acmesolver:1.10.1
* [ ] airflow:2.4.3
  ❌  airflow.2.4.3-0
  ❌  postgresql-client.11.18.0-0
* [ ] airflow-exporter:0.20220314.0
  ❌  airflow-exporter.0.20220314.0-153
* [ ] airflow-scheduler:2.4.3
  ❌  airflow-scheduler.2.4.3-0
  ❌  postgresql-client.11.18.0-0
* [ ] airflow-worker:2.4.3
  ❌  postgresql-client.11.18.0-0
  ❌  airflow-worker.2.4.3-0
* [ ] alertmanager:0.24.0
  ❌  alertmanager.0.24.0-156
* [ ] apache:2.4.54
* [x] apache-exporter:0.11.0
* [ ] appsmith:1.8.10
  ❌  appsmith.1.8.10-0
* [ ] argo-cd:2.5.2
  ❌  kustomize.4.5.7-3
  ❌  argo-cd.2.5.2-1
  ❌  helm.3.10.2-0
  ❌  ksonnet.0.13.1-154
* [ ] argo-workflow-cli:3.4.3
  ❌  argo-workflows.3.4.3-0
* [ ] argo-workflow-controller:3.4.3
  ❌  argo-workflow-controller.3.4.3-0
* [ ] argo-workflow-exec:3.4.3
  ❌  argo-workflow-exec.3.4.3-0
* [ ] aspnet-core:6.0.11
  ❌  aspnet-core.6.0.11-1
* [ ] aspnet-core:7.0.0
  ❌  aspnet-core.7.0.0-1
* [ ] aws-cli:1.27.16
  ❌  aws-cli.1.27.16-0
* [ ] aws-cli:2.9.1
  ❌  aws-cli.2.9.1-0
* [ ] azure-cli:2.42.0
  ❌  azure-cli.2.42.0-0
* [x] bitnami-shell:11.0.0
* [ ] blackbox-exporter:0.22.0
  ❌  blackbox-exporter.0.22.0-3
* [x] cainjector:1.10.1
* [ ] cassandra:4.0.7
  ❌  cassandra.4.0.7-0
* [ ] cassandra-exporter:2.3.8
  ❌  cassandra-exporter.2.3.8-155
* [x] cert-manager:1.10.1
* [x] cert-manager-webhook:1.10.1
* [ ] chartmuseum:0.15.0
  ❌  chartmuseum.0.15.0-3
* [ ] clickhouse:22.3.14
  ❌  clickhouse.22.3.14-0
* [ ] clickhouse:22.5.4
  ❌  clickhouse.22.5.4-1
* [ ] clickhouse:22.6.9
  ❌  clickhouse.22.6.9-0
* [ ] clickhouse:22.7.7
  ❌  clickhouse.22.7.7-0
* [ ] clickhouse:22.8.9
  ❌  clickhouse.22.8.9-0
* [ ] clickhouse:22.9.5
  ❌  clickhouse.22.9.5-0
* [ ] cluster-autoscaler:1.25.0
  ❌  cluster-autoscaler.1.25.0-1
* [ ] codeigniter:4.2.10
  ❌  codeigniter.4.2.10-0
* [ ] concourse:7.8.3
  ❌  concourse.7.8.3-1
* [ ] configmap-reload:0.8.0
  ❌  configmap-reload.0.8.0-0
* [ ] configurable-http-proxy:4.5.3
  ❌  configurable-http-proxy.4.5.3-1
* [x] consul:1.14.1
* [x] consul-exporter:0.8.0
* [x] contour:1.21.1
* [x] contour:1.22.1
* [ ] contour:1.23.0
  ❌  contour.1.23.0-1
* [x] contour-operator:1.21.1
* [x] contour-operator:1.22.1
* [ ] contour-operator:1.23.0
  ❌  contour-operator.1.23.0-1
* [ ] cosign:1.13.1
  ❌  cosign.1.13.1-0
* [ ] couchdb:3.2.2
  ❌  couchdb.3.2.2-162
* [ ] dex:2.35.3
  ❌  dex.2.35.3-0
* [x] discourse:2.8.11
* [ ] dokuwiki:20220731.1.0
  ❌  dokuwiki.20220731.1.0-4
* [ ] dotnet:6.0.11
  ❌  dotnet.6.0.11-1
* [ ] dotnet:7.0.0
  ❌  dotnet.7.0.0-1
* [ ] dotnet-sdk:6.0.403
  ❌  dotnet-sdk.6.0.403-1
* [ ] dotnet-sdk:7.0.100
  ❌  dotnet-sdk.7.0.100-1
* [ ] dreamfactory:4.12.0
  ❌  postgresql-client.11.18.0-0
  ❌  redis-client.7.0.5-1
  ❌  dreamfactory.4.12.0-4
* [ ] drupal:9.4.8
  ❌  drupal.9.4.8-4
* [ ] drupal-nginx:7.92.0
  ❌  drupal.7.92.0-4
* [ ] drupal-nginx:9.4.8
  ❌  drupal.9.4.8-4
* [ ] ejbca:7.10.0
  ❌  ejbca.7.10.0-2-1
  ❌  wildfly.26.1.2-3
* [x] elasticsearch:7.17.7
* [ ] elasticsearch:8.5.2
  ❌  elasticsearch.8.5.2-1
* [x] elasticsearch-exporter:1.5.0
* [x] envoy:1.21.5
* [x] envoy:1.22.5
* [x] envoy:1.23.2
* [ ] envoy:1.24.0
  ❌  envoy.1.24.0-0
* [ ] envoy-intel:1.21.5
  ❌  envoy-intel.1.21.5-0
* [x] etcd:3.3.27
* [x] etcd:3.4.22
* [x] etcd:3.5.6
* [ ] express:4.18.2
  ❌  express-generator.4.16.1-155
  ❌  sequelize-cli.6.5.2-0
  ❌  bower.1.8.13-1
  ❌  express.4.18.2-0
* [x] external-dns:0.13.1
* [ ] fluent-bit:1.9.9
  ❌  fluent-bit.1.9.9-1
* [ ] fluent-bit:2.0.6
  ❌  fluent-bit.2.0.6-0
* [x] fluentd:1.15.3
* [ ] geode:1.15.1
  ❌  geode.1.15.1-0
* [ ] ghost:4.48.8
  ❌  ghost.4.48.8-0
* [ ] ghost:5.23.0
  ❌  ghost.5.23.0-0
* [x] git:2.38.1
* [ ] gitea:1.17.3
  ❌  gitea.1.17.3-0
* [ ] gitlab-runner:15.6.1
  ❌  docker-machine.0.16.2-154
  ❌  dumb-init.1.2.5-154
  ❌  gitlab-runner.15.6.1-0
* [ ] gitlab-runner-helper:15.6.1
  ❌  dumb-init.1.2.5-154
  ❌  gitlab-runner-helper.15.6.1-0
* [ ] golang:1.18.8
  ❌  golang.1.18.8-0
* [ ] golang:1.19.3
  ❌  golang.1.19.3-0
* [ ] google-cloud-sdk:0.410.0
  ❌  google-cloud-sdk.0.410.0-0
* [ ] gradle:7.5.1
  ❌  gradle.7.5.1-4
* [ ] grafana:9.2.6
  ❌  grafana.9.2.6-0
* [ ] grafana-image-renderer:3.6.2
  ❌  grafana-image-renderer.3.6.2-1
* [ ] grafana-loki:2.7.0
  ❌  grafana-loki.2.7.0-1
* [ ] grafana-operator:4.7.1
  ❌  grafana-operator.4.7.1-1
* [ ] grafana-tempo:1.5.0
  ❌  grafana-tempo.1.5.0-3
* [ ] grafana-tempo-query:1.5.0
  ❌  grafana-tempo-query.1.5.0-3
  ❌  jaeger-query.1.38.1-1
* [ ] grafana-tempo-vulture:1.5.0
  ❌  grafana-tempo-vulture.1.5.0-3
* [ ] gramine-redis-intel:1.3.1
  ❌  gramine-redis-intel.1.3.1-0
* [ ] haproxy:2.6.6
  ❌  haproxy-dataplaneapi.2.6.1-1
  ❌  haproxy.2.6.6-1
* [ ] haproxy-intel:2.6.6
  ❌  haproxy.2.6.6-1
  ❌  haproxy-dataplaneapi.2.6.1-1
  ❌  qatengine.0.6.17-0
* [ ] harbor-adapter-trivy:2.6.2
  ❌  harbor-adapter-trivy.2.6.2-0
* [ ] harbor-core:2.6.2
  ❌  harbor-core.2.6.2-0
* [ ] harbor-exporter:2.6.2
  ❌  harbor-exporter.2.6.2-0
* [ ] harbor-jobservice:2.6.2
  ❌  harbor-jobservice.2.6.2-0
* [ ] harbor-notary-server:2.6.2
  ❌  harbor-notary-server.2.6.2-0
* [ ] harbor-notary-signer:2.6.2
  ❌  harbor-notary-signer.2.6.2-0
* [ ] harbor-portal:2.6.2
  ❌  harbor.2.6.2-0
* [ ] harbor-registry:2.6.2
  ❌  harbor-registry.2.6.2-0
* [ ] harbor-registryctl:2.6.2
  ❌  harbor-registry.2.6.2-0
  ❌  harbor-registryctl.2.6.2-0
* [ ] inc-intel:1.14.2
  ❌  inc-intel.1.14.2-0
* [ ] inc-tensorflow-intel:1.14.2
  ❌  inc-tensorflow-intel.1.14.2-0
* [ ] influxdb:2.5.1
  ❌  influxdb.2.5.1-0
* [ ] jaeger:1.39.0
  ❌  jaeger.1.39.0-3
* [ ] jasperreports:8.1.0
  ❌  jasperreports.8.1.0-2
  ❌  postgresql-client.11.18.0-0
* [x] java:1.8.352
* [x] java:11.0.17
* [x] java:17.0.5
* [ ] java:19.0.1
  ❌  java.19.0.1-11-2
* [ ] jenkins:2.361.4
  ❌  jenkins.2.361.4-0
* [x] jmx-exporter:0.17.2
* [ ] joomla:3.10.11
  ❌  joomla.3.10.11-3
* [ ] joomla:4.2.5
  ❌  joomla.4.2.5-1
* [ ] jruby:9.3.9
  ❌  jruby.9.3.9-0-2
* [ ] jsonnet:0.19.1
  ❌  jsonnet.0.19.1-0
* [ ] jupyter-base-notebook:3.0.0
  ❌  jupyter-base-notebook.3.0.0-5
  ❌  miniconda.4.12.0-158
  ❌  tini.0.19.0-155
* [ ] jupyterhub:3.0.0
  ❌  jupyterhub.3.0.0-4
  ❌  miniconda.4.12.0-158
* [x] kafka:3.1.2
* [x] kafka:3.2.3
* [x] kafka:3.3.1
* [x] kafka-exporter:1.6.0
* [ ] kapacitor:1.6.5
  ❌  kapacitor.1.6.5-2
* [x] keycloak:19.0.3
* [ ] keycloak:20.0.1
  ❌  keycloak.20.0.1-0
* [x] keycloak-config-cli:5.5.0
* [ ] kiam:4.2.0
  ❌  kiam.4.2.0-154
* [ ] kibana:7.17.7
  ❌  kibana.7.17.7-0
* [ ] kibana:8.5.2
  ❌  kibana.8.5.2-0
* [ ] kong:3.0.1
  ❌  kong.3.0.1-9
* [ ] kong-ingress-controller:2.7.0
  ❌  kong-ingress-controller.2.7.0-1
* [ ] ksql:6.1.8
  ❌  ksql.6.1.8-1
* [ ] ksql:6.2.7
  ❌  ksql.6.2.7-1
* [ ] ksql:7.0.6
  ❌  ksql.7.0.6-1
* [ ] ksql:7.1.4
  ❌  ksql.7.1.4-1
* [ ] ksql:7.2.2
  ❌  ksql.7.2.2-1
* [ ] ksql:7.3.0
  ❌  ksql.7.3.0-0
* [ ] kube-rbac-proxy:0.13.1
  ❌  kube-rbac-proxy.0.13.1-1
* [ ] kube-state-metrics:2.6.0
  ❌  kube-state-metrics.2.6.0-2
* [ ] kubeapps-apis:2.6.1
  ❌  kubeapps-apis.2.6.1-0
* [ ] kubeapps-apprepository-controller:2.6.1
  ❌  kubeapps-apprepository-controller.2.6.1-0
* [ ] kubeapps-asset-syncer:2.6.1
  ❌  kubeapps-asset-syncer.2.6.1-0
* [ ] kubeapps-dashboard:2.6.1
  ❌  kubeapps.2.6.1-0
* [ ] kubeapps-pinniped-proxy:2.6.1
  ❌  kubeapps-pinniped-proxy.2.6.1-0
* [x] kubectl:1.23.14
* [x] kubectl:1.24.8
* [x] kubectl:1.25.4
* [ ] kubernetes-event-exporter:1.0.0
  ❌  kubernetes-event-exporter.1.0.0-1
* [ ] laravel:9.3.12
  ❌  laravel.9.3.12-0
* [ ] logstash:7.17.7
  ❌  logstash.7.17.7-0
* [ ] logstash:8.5.2
  ❌  logstash.8.5.2-0
* [ ] magento:2.4.5
  ❌  magento.2.4.5-p1-14
* [ ] mariadb:10.10.2
  ❌  mariadb.10.10.2-3
* [ ] mariadb:10.3.37
  ❌  mariadb.10.3.37-3
* [ ] mariadb:10.4.27
  ❌  mariadb.10.4.27-2
* [x] mariadb:10.5.18
* [x] mariadb:10.6.11
* [x] mariadb:10.7.7
* [x] mariadb:10.8.6
* [ ] mariadb:10.9.4
  ❌  mariadb.10.9.4-1
* [ ] mariadb-galera:10.10.2
  ❌  mariadb-galera.10.10.2-2
* [ ] mariadb-galera:10.3.37
  ❌  mariadb-galera.10.3.37-2
* [ ] mariadb-galera:10.4.27
  ❌  mariadb-galera.10.4.27-2
* [x] mariadb-galera:10.5.18
* [x] mariadb-galera:10.6.11
* [x] mariadb-galera:10.7.7
* [x] mariadb-galera:10.8.6
* [ ] mariadb-galera:10.9.4
  ❌  mariadb-galera.10.9.4-2
* [ ] matomo:4.12.3
  ❌  matomo.4.12.3-1
* [ ] mediawiki:1.38.4
  ❌  mediawiki.1.38.4-2
* [x] memcached:1.6.17
* [x] memcached-exporter:0.10.0
* [ ] metallb-controller:0.13.7
  ❌  metallb.0.13.7-0
* [ ] metallb-speaker:0.13.7
  ❌  metallb-speaker.0.13.7-0
* [ ] metrics-server:0.6.1
  ❌  metrics-server.0.6.1-154
* [x] minio:2022.11.17
* [x] minio-client:2022.11.17
* [x] mongodb:5.0.14
* [x] mongodb:6.0.3
* [x] mongodb-exporter:0.35.0
* [x] mongodb-sharded:5.0.14
* [x] mongodb-sharded:6.0.3
* [ ] moodle:3.11.11
  ❌  moodle.3.11.11-1
  ❌  postgresql-client.13.9.0-0
* [ ] moodle:4.0.5
  ❌  moodle.4.0.5-1
  ❌  postgresql-client.13.9.0-0
* [ ] mxnet:1.9.1
  ❌  mxnet.1.9.1-156
* [ ] mysql:5.7.40
  ❌  mysql.5.7.40-1
* [x] mysql:8.0.31
* [x] mysqld-exporter:0.14.0
* [ ] nats:2.9.8
  ❌  nats.2.9.8-0
* [ ] nats-exporter:0.10.1
  ❌  nats-exporter.0.10.1-0
* [ ] neo4j:4.4.14
  ❌  neo4j.4.4.14-1
* [ ] neo4j:5.2.0
  ❌  neo4j.5.2.0-1
* [ ] nginx:1.22.1
  ❌  nginx.1.22.1-1
* [x] nginx:1.23.2
* [x] nginx-exporter:0.11.0
* [ ] nginx-ingress-controller:1.5.1
  ❌  nginx-ingress-controller.1.5.1-0
* [ ] nginx-intel:0.4.9
  ❌  nginx-intel.0.4.9-0
  ❌  qatengine.0.6.17-0
* [x] node:14.21.1
* [x] node:16.18.1
* [x] node:18.12.1
* [ ] node-exporter:1.4.0
  ❌  node-exporter.1.4.0-1
* [ ] oauth2-proxy:7.4.0
  ❌  oauth2-proxy.7.4.0-0
* [ ] odoo:14.0.20221110
  ❌  postgresql-client.13.9.0-0
  ❌  odoo.14.0.20221110-1
* [ ] odoo:15.0.20221110
  ❌  odoo.15.0.20221110-1
  ❌  postgresql-client.13.9.0-0
* [ ] odoo:16.0.20221115
  ❌  odoo.16.0.20221115-1
  ❌  postgresql-client.13.9.0-0
* [ ] opencart:4.0.1
  ❌  opencart.4.0.1-1-2
* [ ] openldap:2.5.13
  ❌  openldap.2.5.13-6
* [x] openldap:2.6.3
* [ ] openresty:1.21.4
  ❌  openresty.1.21.4-1-154
* [ ] oras:0.16.0
  ❌  oras.0.16.0-0
* [ ] osclass:8.0.2
  ❌  osclass.8.0.2-155
* [ ] owncloud:10.11.0
  ❌  owncloud.10.11.0-2
* [ ] parse:5.4.0
  ❌  parse.5.4.0-0
* [ ] parse-dashboard:5.0.0
  ❌  parse-dashboard.5.0.0-0
* [ ] percona-mysql:5.7.39
  ❌  percona-xtrabackup-binary.8.0.30-23-0
  ❌  mysql-shell.8.0.31-1
  ❌  percona-mysql.5.7.39-42-3
* [ ] percona-mysql:8.0.30
  ❌  mysql-shell.8.0.31-1
  ❌  percona-mysql.8.0.30-22-1
  ❌  percona-xtrabackup-binary.8.0.30-23-0
* [ ] percona-xtrabackup:2.4.26
  ❌  percona-xtrabackup.2.4.26-155
* [ ] percona-xtrabackup:8.0.30
  ❌  percona-xtrabackup.8.0.30-23-0
* [ ] pgbouncer:1.17.0
  ❌  pgbouncer.1.17.0-157
* [x] pgpool:4.3.3
* [ ] php-fpm:7.4.33
* [ ] php-fpm:8.0.26
* [ ] php-fpm:8.1.13
* [ ] phpbb:3.3.8
  ❌  phpbb.3.3.8-5
* [ ] phpmyadmin:5.2.0
  ❌  phpmyadmin.5.2.0-155
* [ ] pinniped:0.20.0
  ❌  pinniped.0.20.0-4
* [x] postgres-exporter:0.11.1
* [x] postgresql:11.18.0
* [x] postgresql:12.13.0
* [x] postgresql:13.9.0
* [x] postgresql:14.6.0
* [ ] postgresql:15.1.0
  ❌  postgresql.15.1.0-0
* [x] postgresql-repmgr:11.18.0
* [x] postgresql-repmgr:12.13.0
* [x] postgresql-repmgr:13.9.0
* [x] postgresql-repmgr:14.6.0
* [ ] postgresql-repmgr:15.1.0
  ❌  postgresql-repmgr.15.1.0-0
* [ ] prestashop:8.0.0
  ❌  prestashop.8.0.0-1
* [ ] prometheus:2.40.3
  ❌  prometheus.2.40.3-0
* [ ] prometheus-operator:0.61.1
  ❌  prometheus-operator.0.61.1-0
* [ ] prometheus-rsocket-proxy:1.5.0
  ❌  prometheus-rsocket-proxy.1.5.0-2
* [ ] promtail:2.7.0
  ❌  promtail.2.7.0-1
* [ ] pushgateway:1.5.0
  ❌  pushgateway.1.5.0-0
* [x] python:3.10.8
* [x] python:3.11.0
* [x] python:3.7.15
* [x] python:3.8.15
* [x] python:3.9.15
* [ ] pytorch:1.13.0
  ❌  pytorch.1.13.0-0
* [ ] pytorch-intel:1.12.1
  ❌  pytorch-intel.1.12.1-7
* [ ] pytorch-intel:1.12.300
  ❌  pytorch-intel.1.12.300-0
* [x] rabbitmq:3.10.11
* [x] rabbitmq:3.11.3
* [x] rabbitmq:3.9.25
* [x] rabbitmq-cluster-operator:2.0.0
* [ ] rails:6.1.7
  ❌  rails.6.1.7-0-1
* [ ] rails:7.0.4
  ❌  rails.7.0.4-0-2
* [ ] rclone:1.60.1
  ❌  rclone.1.60.1-0
* [x] redis:6.2.7
* [x] redis:7.0.5
* [x] redis-cluster:6.2.7
* [x] redis-cluster:7.0.5
* [x] redis-exporter:1.45.0
* [x] redis-sentinel:6.2.7
* [x] redis-sentinel:7.0.5
* [ ] redmine:5.0.3
  ❌  postgresql-client.11.18.0-0
  ❌  redmine.5.0.3-2
* [ ] reportserver:4.3.0
  ❌  reportserver.4.3.0-6080-0
* [x] rmq-default-credential-updater:1.0.2
* [x] rmq-messaging-topology-operator:1.9.0
* [ ] ruby:2.7.7
* [ ] ruby:3.0.5
* [ ] ruby:3.1.3
* [ ] schema-registry:6.1.8
  ❌  schema-registry.6.1.8-1
* [ ] schema-registry:6.2.7
  ❌  schema-registry.6.2.7-1
* [ ] schema-registry:7.0.6
  ❌  schema-registry.7.0.6-1
* [ ] schema-registry:7.1.4
  ❌  schema-registry.7.1.4-1
* [ ] schema-registry:7.2.2
  ❌  schema-registry.7.2.2-1
* [ ] schema-registry:7.3.0
  ❌  schema-registry.7.3.0-0
* [ ] scikit-learn-intel:2021.7.1
  ❌  scikit-learn-intel.2021.7.1-0
* [x] sealed-secrets:0.19.2
* [x] solr:8.11.2
* [x] solr:9.1.0
* [ ] sonarqube:8.9.10
  ❌  postgresql-client.13.9.0-0
  ❌  sonarqube.8.9.10-1
* [ ] sonarqube:9.7.1
  ❌  postgresql-client.13.9.0-0
  ❌  sonarqube.9.7.1-1
* [ ] spark:3.2.2
  ❌  spark.3.2.2-6
* [ ] spark:3.3.1
  ❌  spark.3.3.1-1
* [ ] spring-cloud-dataflow:2.9.6
  ❌  spring-cloud-dataflow.2.9.6-1
* [ ] spring-cloud-dataflow-composed-task-runner:2.9.6
  ❌  spring-cloud-dataflow-composed-task-runner.2.9.6-1
* [ ] spring-cloud-dataflow-shell:2.9.6
  ❌  spring-cloud-dataflow-shell.2.9.6-1
* [ ] spring-cloud-skipper:2.8.6
  ❌  spring-cloud-skipper.2.8.6-1
* [ ] spring-cloud-skipper-shell:2.8.6
  ❌  spring-cloud-skipper-shell.2.8.6-1
* [ ] suitecrm:7.12.8
  ❌  suitecrm.7.12.8-1
* [ ] suitecrm:8.2.1
  ❌  suitecrm.8.2.1-1
* [ ] symfony:4.4.48
  ❌  symfony.4.4.48-0
* [ ] symfony:5.4.15
  ❌  symfony.5.4.15-0
* [ ] symfony:6.0.15
  ❌  symfony.6.0.15-0
* [ ] symfony:6.1.7
  ❌  symfony.6.1.7-0
* [ ] telegraf:1.24.3
  ❌  telegraf.1.24.3-0
* [ ] tensorflow-intel:2.11.0
  ❌  tensorflow-intel.2.11.0-0
* [ ] tensorflow-resnet:2.11.0
  ❌  tensorflow-resnet.2.11.0-0
* [ ] tensorflow-serving:2.11.0
  ❌  tensorflow-serving.2.11.0-0
* [x] thanos:0.29.0
* [x] tomcat:10.0.27
* [ ] tomcat:10.1.2
  ❌  tomcat.10.1.2-1
* [x] tomcat:8.5.84
* [x] tomcat:9.0.69
* [ ] trivy:0.34.0
  ❌  trivy.0.34.0-0
* [ ] wavefront-hpa-adapter:0.9.9
  ❌  wavefront-hpa-adapter.0.9.9-4
* [ ] wavefront-kubernetes-collector:1.12.0
  ❌  wavefront.1.12.0-1
* [ ] wavefront-prometheus-storage-adapter:1.0.5
  ❌  wavefront-prometheus-storage-adapter.1.0.5-155
* [ ] wavefront-proxy:11.4.0
  ❌  wavefront-proxy.11.4.0-2
* [ ] wavefront-proxy:12.0.0
  ❌  wavefront-proxy.12.0.0-0
* [ ] wildfly:26.1.2
  ❌  wildfly.26.1.2-3
* [ ] wildfly:27.0.0
  ❌  wildfly.27.0.0-1
* [x] wordpress:6.1.1
* [ ] wordpress-intel:6.1.1
  ❌  nginx-intel.0.4.9-0
  ❌  qatengine.0.6.17-0
* [x] wordpress-nginx:6.1.1
* [ ] xgboost-intel:1.7.1
  ❌  xgboost-intel.1.7.1-0
* [x] zookeeper:3.6.3
* [x] zookeeper:3.7.1
* [x] zookeeper:3.8.0

Generated from
```
go run main.go list
```

## Todo

* [ ] CI update this issue.
* [x] #49

**Comment by ZCube** [comment]
I'm closing this issue because I think it's better to keep this as a document in the repository.
