### ISSUE TITLE
Add Vulnerability Scanner and Publish Results

### ISSUE THREAD

**Issue by ZCube** [ZCube/bitnami-compat#46]
### Todo

* [ ] Add triviy scanner result to branch in json format. ( example branch : trivy/nginx  file : trivy_result.json )
* [ ] Convert Json to markdown format.
* [ ] Publish using https://github.com/dbsystel/trivy-vulnerability-explorer.

### Reference

* https://github.com/dbsystel/trivy-vulnerability-explorer
